# Generated by Django 3.1.5 on 2021-03-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20210316_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
